In [4]:
import pandas as pd

# Buat dataset
data = {
    'Country': ['France', 'Spain', 'Germany', 'Spain', 'Germany', 
                'France', 'Spain', 'France', 'Germany', 'France'],
    'Age': [44, 27, 30, 38, 40, 35, 52, 48, 50, 37],
    'Salary': [72000, 48000, 54000, 61000, 61000, 
               58000, 52000, 79000, 83000, 67000],
    'Purchased': ['No', 'Yes', 'No', 'No', 'Yes', 
                  'Yes', 'No', 'Yes', 'No', 'Yes']
}

# Convert ke DataFrame
df = pd.DataFrame(data)

# Simpan sebagai CSV di lokasi yang Anda tentukan
df.to_csv('D:\\smt5\\penambangan data\\tugas 3\\Data.csv', index=False)


print("Data berhasil disimpan di D:\smt5\penambangan data\tugas 3\Data.csv")


Data berhasil disimpan di D:\smt5\penambangan data	ugas 3\Data.csv


<>:21: SyntaxWarning: invalid escape sequence '\s'
<>:21: SyntaxWarning: invalid escape sequence '\s'
C:\Users\User\AppData\Local\Temp\ipykernel_10628\1409906347.py:21: SyntaxWarning: invalid escape sequence '\s'
  print("Data berhasil disimpan di D:\smt5\penambangan data\tugas 3\Data.csv")


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('D:\\smt5\\penambangan data\\tugas 3\\Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(x)
print(y)



[['France' 44 72000]
 ['Spain' 27 48000]
 ['Germany' 30 54000]
 ['Spain' 38 61000]
 ['Germany' 40 61000]
 ['France' 35 58000]
 ['Spain' 52 52000]
 ['France' 48 79000]
 ['Germany' 50 83000]
 ['France' 37 67000]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


NameError: name 'X' is not defined

In [10]:
from sklearn.impute import SimpleImputer
import numpy as np
import pandas as pd

# Baca file CSV dengan path yang benar
dataset = pd.read_csv(r'D:\smt5\penambangan data\tugas 3\Data.csv')

# Ambil fitur (x) dan label (y)
x = dataset.iloc[:, :-1].values   # Semua kolom kecuali kolom terakhir
y = dataset.iloc[:, -1].values    # Kolom terakhir

# Mengatasi missing values (imputer)
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# Fit imputer ke kolom yang berisi data numerik (contohnya kolom 1 dan 2)
imputer.fit(x[:, 1:3])

# Transformasi data pada kolom yang berisi missing values
x[:, 1:3] = imputer.transform(x[:, 1:3])

print(x)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 61000.0]
 ['France' 35.0 58000.0]
 ['Spain' 52.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Definisi ColumnTransformer dengan OneHotEncoder untuk kolom pertama
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

# Transformasi x dengan OneHotEncoder pada kolom pertama
x = np.array(ct.fit_transform(x))

print(x)


[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 61000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 52.0 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [17]:
from sklearn.preprocessing import LabelEncoder
Le = LabelEncoder()  # Corrected the typo here
y = Le.fit_transform(y)
print(y)


[0 1 0 0 1 1 0 1 0 1]


In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
print(X_train)
print(X_test)
print(y_train)
print(y_test)


   feature1  feature2
1         2         4
4         5         1
0         1         5
3         4         2
   feature1  feature2
2         3         3
1    1
4    0
0    0
3    1
Name: label, dtype: int64
2    0
Name: label, dtype: int64


In [39]:
# Import library yang dibutuhkan
from sklearn.preprocessing import StandardScaler
import numpy as np

# Contoh dataset
X_train = np.array([[0.0, 0.0, 1.0, 0.19159184384578545, -1.0781259408412425],
                    [0.0, 1.0, 0.0, 0.014117293757057777, -0.07013167641635372],
                    [1.0, 0.0, 0.0, -0.566708506533324, 0.633562432710455],
                    [0.0, 0.0, 1.0, -0.39450319990224867, -0.30786817072429787],
                    [0.0, 1.0, 0.0, -0.1918301410740971, -1.232643363551582],
                    [1.0, 0.0, 0.0, 0.4394742060986881, 1.574913080363885],
                    [0.0, 0.0, 1.0, 2.0244109454142023, -0.5646194287757323]])

X_test = np.array([[0.0, 0.0, 1.0, 1.4661817944830124, -0.0969571034860727],
                   [1.0, 0.0, 0.0, -0.44973664397484414, 0.205640339225306]])

# Inisialisasi StandardScaler
sc = StandardScaler()

# Fit dan transform data X_train pada kolom ke-3 hingga akhir
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])

# Transform data X_test pada kolom ke-3 hingga akhir
X_test[:, 3:] = sc.transform(X_test[:, 3:])

# Cetak hasil transformasi
print("X_train after scaling:")
print(X_train)

print("\nX_test after scaling:")
print(X_test)


X_train after scaling:
[[ 0.          0.          1.         -0.03120732 -1.01814408]
 [ 0.          1.          0.         -0.25223029  0.08674957]
 [ 1.          0.          0.         -0.97557817  0.85809043]
 [ 0.          0.          1.         -0.76111741 -0.17384074]
 [ 0.          1.          0.         -0.50871277 -1.1875154 ]
 [ 1.          0.          0.          0.27750001  1.88993396]
 [ 0.          0.          1.          2.25134594 -0.45527373]]

X_test after scaling:
[[ 0.          0.          1.          1.55613943  0.05734539]
 [ 1.          0.          0.         -0.82990395  0.3890318 ]]
